# Generated by Django 5.2.3 on 2025-06-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_uploadedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labimage',
            name='image',
            field=models.ImageField(upload_to='labs/images/'),
        ),
    ]
