# Generated by Django 5.2.3 on 2025-06-16 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_labimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labimage',
            name='uploaded_by',
        ),
        migrations.DeleteModel(
            name='UploadedImage',
        ),
        migrations.DeleteModel(
            name='LabImage',
        ),
    ]
