# Generated by Django 5.2.3 on 2025-06-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_labimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labimage',
            name='file',
            field=models.FileField(upload_to='lab_images/'),
        ),
    ]
