# Generated by Django 5.2.3 on 2025-06-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_labimage_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='evelabfile',
            name='lab_type',
            field=models.CharField(choices=[('EVE', 'EVE Lab'), ('CML', 'CML Lab'), ('PT', 'Packet Tracer Lab')], default='EVE', max_length=3),
        ),
    ]
